version: '2'
services:
    matrimony-app:
        image: matrimony
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://matrimony-mysql:3306/matrimony?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    matrimony-mysql:
        extends:
            file: mysql.yml
            service: matrimony-mysql
